theme: jekyll-theme-minimal
title: UChicago Physics Department Coding Club
description: The Coding Club provides a forum for students to gain, build, and strengthen their scientific programming and analysis skills in a social and collaborative environment. With the guidance of faculty mentors, students read actual scientific publications and analyze results, reinterpret the data, or even extend the approaches considered.
logo: https://d3qi0qp55mx5f5.cloudfront.net/shared-resources/i/template/uc_wordmark_hires.gif
show_downloads: true
