theme: jekyll-theme-minimal
title: UChicago Physics Department Coding Club
description: A forum for students to gain, build, and strengthen their scientific computing skills by reading scientific publications and reproducing results, reinterpreting the data, and exercising the computational approaches used.
logo: https://d3qi0qp55mx5f5.cloudfront.net/shared-resources/i/template/uc_wordmark_hires.gif
show_downloads: false
base-url: CodingClub
